[change] Switch to iwinfo to get associated clients if mesh or adhoc
openwisp/lua-monitoring pull request #23
Opened 2021-01-11 15:23 UTC by R9295

implements #21

2021-01-13 03:50 UTC, nemesisdesign reviewed
Thanks @R9295! It looks good.
I need some more time to test it, but before doing that, let me know if you have tested it on openwisp-monitoring and if something needs to be done in https://github.com/openwisp/openwisp-monitoring/issues/260 to make it work there.

2021-01-13 09:05 UTC, R9295 commented
Will do

2021-01-16 01:50 UTC, nemesisdesign reviewed
Great work @R9295 :+1: 

I tested it with openwisp-monitoring, the schema needs to be relaxed a bit:

```
"Invalid data in \"#/interfaces/4/wireless/clients/0\", validator says:\n\n'aid' is a required property"r
```

Can you take care of this change? (https://github.com/openwisp/openwisp-monitoring/issues/260)

2021-01-18 00:11 UTC, nemesisdesign requested changes

2021-01-18 00:11 UTC, nemesisdesign commented on Makefile
> +$(eval $(call BuildPackage,openwrt-netjson-monitoring))
Let's not add this now, it's not related to the issue we're working on

2021-01-18 00:11 UTC, nemesisdesign commented on files/monitoring-crontab
> +  */5 * * * * /usr/sbin/openwisp-monitoring
same here

2021-01-18 00:18 UTC, R9295 commented
@nemesisdesign whoops, I accidentally pushed that to master and not my dev branch 😳

2021-01-18 00:18 UTC, nemesisdesign commented
> @nemesisdesign whoops, I accidentally pushed that to master and not my dev branch

Ah ok, I suspected that, no problem.

2021-01-18 00:32 UTC, nemesisdesign reviewed
Tested with https://github.com/openwisp/openwisp-monitoring/pull/263 and it works, thanks! :+1: :+1: 
I will wait for you to clean up the mistakenly added commit before merging.

2021-01-18 14:56 UTC, nemesisdesign approved these changes
Great work @R9295, thanks!

2021-01-18 14:57 UTC, merged